// Copyright 2026 M. Javani
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package verifier

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"math/big"
	"net/url"
	"testing"
	"time"
)

func generateX509Certificate(opts certOptions) (*x509.Certificate, error) {
	// Convert URI strings to url.URL objects
	var uris []*url.URL
	for _, uriStr := range opts.uris {
		uri, err := url.Parse(uriStr)
		if err != nil {
			return nil, err
		}
		uris = append(uris, uri)
	}

	// Create certificate template
	template := &x509.Certificate{
		SerialNumber: big.NewInt(1),
		Subject: pkix.Name{
			CommonName: opts.commonName,
		},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(time.Hour),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
		DNSNames:              opts.dnsNames,
		URIs:                  uris,
		BasicConstraintsValid: true,
		IsCA:                  false,
	}
	return template, nil
}

// generateTestCertDER creates a self-signed certificate and returns DER-encoded bytes
// This matches what you get from cert.Raw in TLS connections
func generateTestCertDER(opts certOptions) ([]byte, error) {
	// Generate private key
	privateKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return nil, err
	}

	template, err := generateX509Certificate(opts)
	if err != nil {
		return nil, err
	}
	// Self-sign the certificate and return DER bytes
	certDER, err := x509.CreateCertificate(rand.Reader, template, template, &privateKey.PublicKey, privateKey)
	if err != nil {
		return nil, err
	}

	return certDER, nil
}

type certOptions struct {
	commonName string
	dnsNames   []string
	uris       []string // URI SANs as strings (will be converted to *url.URL)
}

// Test that all verifiers implement the interface
func TestVerifiersImplementInterface(t *testing.T) {
	var _ TLSVerifier = DNSVerifier{}
	var _ TLSVerifier = SPIFFEVerifier{}
	var _ TLSVerifier = CNVerifier{}
}

// Test that certificates generated by our test helper are valid
func TestGenerateTestCert(t *testing.T) {
	certDER, err := generateTestCertDER(certOptions{
		commonName: "test-node",
		dnsNames:   []string{"test-node.local"},
		uris:       []string{"spiffe://test.org/test/test-node"},
	})
	if err != nil {
		t.Fatalf("failed to generate test cert: %v", err)
	}

	if len(certDER) == 0 {
		t.Error("expected non-empty certificate data")
	}

	// Verify we can parse it (should work with DER)
	_, err = x509.ParseCertificate(certDER)
	if err != nil {
		t.Errorf("failed to parse generated certificate: %v", err)
	}
}

// Example of using the verifier package
func ExampleDNSVerifier() {
	v := DNSVerifier{Domain: "cluster.local"}
	_ = v
}
